### ISSUE TITLE
Unit Conversions riddle disconnects the app

### ISSUE THREAD

**Issue by ghost** [dgkf/riddlr#1]
hi @dgkf,

Thanks for a nice package and app! I did all 3 riddles :) For some reason the Unit Conversions disconnects my session when I submit the following solution. If you have a chance to see the log in shinyapps.io that would be great to know what's going on.

```r
new_ages <- vector("character")

for (age in ages) {
  for (u_i in seq_along(conversions)) {
    new_age <- trunc(age * conversions[u_i], 1)
    if (new_age >= 1) {
      suffix <- ""
      if (new_age > 1) suffix <- "s"
      char_it <- paste(new_age, paste0(names(conversions)[u_i], suffix), "old")
      print(char_it)
      new_ages = append(new_ages, char_it)
      break
    }
  }
}

new_ages
```

![image](https://user-images.githubusercontent.com/7897325/86553892-01e41080-bf1a-11ea-8936-5e745f8f6346.png)

**Comment by dgkf** [comment]
@armenic Thanks for filing this. I'll dig into it and try to figure out what might be causing the server issues.

**Comment by dgkf** [comment]
Just a quick follow-up, this is GREAT! You've made a solution that falls within the "grace window" before timing out, meaning that your solution computes correctly and completed, but still took _slightly_ too long to be considered "right". This is a hard situation to nail down, so it was definitely undertested when I was developing the app. Ideally, it should give you a little message that communicates all of this, but it's failing because it seems I have a typo in the message creation for this one rare message type. 

https://github.com/dgkf/riddlr/blob/f0ab86d522db1aa3ca6b1591a740efd03af5c114/R/grade_riddle.R#L301-L307

Turns out there's no function called "ssf" and that's what's causing the error. Most likely I had s*print*f highlighted and hit s. I'm sure at one point I was wondering why my "s" key wasn't registering where I thought my cursor was.

**Comment by dgkf** [comment]
It's updated now on shinyapps.io - feel free to give it a go and test it out for yourself. Hopefully it gets past the error to communicate the new challenge of optimizing your calculation a bit :) 

https://dgkf.shinyapps.io/riddlr-challenge-catalog/

When you're ready, you can also take a look at how the questions are formatted, making it easy to add new ones. The code for the solutions, at least for the examples, can be found within the package if you dig around a bit:

https://github.com/dgkf/riddlr/blob/master/inst/example/questions/q3.riddlr.Rmd

**Comment by ghost** [comment]
Nice job Doug! Passed the 3rd riddle as well :) I had to remove the print statement and created a vector with predefined length to plug numbers in. I want to admit, it is very motivating and I wanted to complete all of them. I imagine if we use sdtm, adam related riddles all our colleagues will be stuck on the screens.
I will further explore the package to learn how to create customized riddles.
